---
- hosts: all
  tasks:
    - name: Install Latest zip packages
      apt:
        name: zip
        state: latest
        update_cache: true
    - name: Install bwm-ng
      apt:
        name: bwm-ng
        state: latest
        update_cache: ture
